// <auto-generated />
using System;
using Immobilienverwaltung_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Immobilienverwaltung_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408192447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.ImmobilienOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BruttoMietRendite")
                        .HasColumnType("float");

                    b.Property<int?>("ImmobilienHausgeldId")
                        .HasColumnType("int");

                    b.Property<string>("ImmobilienName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImmobilienTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImmobilienUeberschuss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Kaufpreis")
                        .HasColumnType("bigint");

                    b.Property<double>("Wohnflaeche")
                        .HasColumnType("float");

                    b.Property<decimal>("ZimmerAnzahl")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienHausgeldId")
                        .IsUnique()
                        .HasFilter("[ImmobilienHausgeldId] IS NOT NULL");

                    b.HasIndex("ImmobilienTypeId");

                    b.ToTable("ImmobilienOverviews", (string)null);
                });

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Hausgeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ImmobilienHausgeld", (string)null);
                });

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImmobilienType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImmobilienTypes", (string)null);
                });

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.ImmobilienOverview", b =>
                {
                    b.HasOne("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Hausgeld", "ImmobilienHausgeld")
                        .WithOne("ImmobilienOverview")
                        .HasForeignKey("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.ImmobilienOverview", "ImmobilienHausgeldId");

                    b.HasOne("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Type", "ImmobilienType")
                        .WithMany("ImmobilienOverviews")
                        .HasForeignKey("ImmobilienTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImmobilienHausgeld");

                    b.Navigation("ImmobilienType");
                });

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Hausgeld", b =>
                {
                    b.OwnsOne("Immobilienverwaltung_Backend.Models.ProzentMonatJahr", "Nicht_Umlagefaehiges_Hausgeld", b1 =>
                        {
                            b1.Property<int>("Immobilien_HausgeldId")
                                .HasColumnType("int");

                            b1.Property<decimal>("inProzent")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("proJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("proMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Immobilien_HausgeldId");

                            b1.ToTable("ImmobilienHausgeld");

                            b1.WithOwner()
                                .HasForeignKey("Immobilien_HausgeldId");
                        });

                    b.OwnsOne("Immobilienverwaltung_Backend.Models.ProzentMonatJahr", "Umlagefaehiges_Hausgeld", b1 =>
                        {
                            b1.Property<int>("Immobilien_HausgeldId")
                                .HasColumnType("int");

                            b1.Property<decimal>("inProzent")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("proJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("proMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Immobilien_HausgeldId");

                            b1.ToTable("ImmobilienHausgeld");

                            b1.WithOwner()
                                .HasForeignKey("Immobilien_HausgeldId");
                        });

                    b.OwnsOne("Immobilienverwaltung_Backend.Models.QuadratmeterMonatJahr", "Hausgeld", b1 =>
                        {
                            b1.Property<int>("Immobilien_HausgeldId")
                                .HasColumnType("int");

                            b1.Property<decimal>("proJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("proMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("proQuadratmeter")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Immobilien_HausgeldId");

                            b1.ToTable("ImmobilienHausgeld");

                            b1.WithOwner()
                                .HasForeignKey("Immobilien_HausgeldId");
                        });

                    b.Navigation("Hausgeld")
                        .IsRequired();

                    b.Navigation("Nicht_Umlagefaehiges_Hausgeld")
                        .IsRequired();

                    b.Navigation("Umlagefaehiges_Hausgeld")
                        .IsRequired();
                });

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Hausgeld", b =>
                {
                    b.Navigation("ImmobilienOverview")
                        .IsRequired();
                });

            modelBuilder.Entity("Immobilienverwaltung_Backend.Features.Immobilien_Overview.Models.Immobilien_Type", b =>
                {
                    b.Navigation("ImmobilienOverviews");
                });
#pragma warning restore 612, 618
        }
    }
}
