// <auto-generated />
using BE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Infrastructure.Migrations
{
    [DbContext(typeof(ImmobilienDbContext))]
    [Migration("20250419140319_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienHausgeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("HausgeldProJahr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HausgeldProMonat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HausgeldProQuadratmeter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImmobilienOverviewId")
                        .HasColumnType("int");

                    b.Property<decimal>("NichtUmlagefaehigesHausgeldInProzent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NichtUmlagefaehigesHausgeldProJahr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NichtUmlagefaehigesHausgeldProMonat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UmlagefaehigesHausgeldInProzent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UmlagefaehigesHausgeldProJahr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UmlagefaehigesHausgeldProMonat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienOverviewId")
                        .IsUnique();

                    b.ToTable("ImmobilienHausgeld");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BruttoMietRendite")
                        .HasColumnType("float");

                    b.Property<string>("ImmobilienName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImmobilienTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImmobilienUeberschuss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Kaufpreis")
                        .HasColumnType("bigint");

                    b.Property<double>("Wohnflaeche")
                        .HasColumnType("float");

                    b.Property<decimal>("ZimmerAnzahl")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienTypeId");

                    b.ToTable("ImmobilienOverviews");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImmobilienTypes");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienHausgeld", b =>
                {
                    b.HasOne("BE.Domain.Entities.ImmobilienOverview", "ImmobilienOverview")
                        .WithOne("ImmobilienHausgeld")
                        .HasForeignKey("BE.Domain.Entities.ImmobilienHausgeld", "ImmobilienOverviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImmobilienOverview");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienOverview", b =>
                {
                    b.HasOne("BE.Domain.Entities.ImmobilienType", "ImmobilienType")
                        .WithMany()
                        .HasForeignKey("ImmobilienTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImmobilienType");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienOverview", b =>
                {
                    b.Navigation("ImmobilienHausgeld")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
