// <auto-generated />
using BE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Infrastructure.Migrations
{
    [DbContext(typeof(ImmobilienDbContext))]
    [Migration("20250525133718_removeBruttomietrenditeProperty")]
    partial class removeBruttomietrenditeProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Domain.Entities.Bruttomietrendite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BruttoMietrendite")
                        .HasColumnType("float");

                    b.Property<int>("ImmobilienOverviewId")
                        .HasColumnType("int");

                    b.Property<long>("Kaufpreis")
                        .HasColumnType("bigint");

                    b.Property<double>("KaufpreisFaktor")
                        .HasColumnType("float");

                    b.Property<double>("Wohnflaeche")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienOverviewId")
                        .IsUnique();

                    b.ToTable("BruttoMietrenditen");
                });

            modelBuilder.Entity("BE.Domain.Entities.Hypothek.ImmobilienHypothek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DarlehensBetrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImmobilienOverviewId")
                        .HasColumnType("int");

                    b.Property<long>("Kaufpreis")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Restschuld")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sollzinsbindung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienOverviewId")
                        .IsUnique();

                    b.ToTable("ImmobilienHypotheken");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienHausgeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImmobilienOverviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienOverviewId")
                        .IsUnique();

                    b.ToTable("ImmobilienHausgeld");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImmobilienName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImmobilienTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImmobilienUeberschuss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Kaufpreis")
                        .HasColumnType("bigint");

                    b.Property<double>("Wohnflaeche")
                        .HasColumnType("float");

                    b.Property<decimal>("ZimmerAnzahl")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImmobilienTypeId");

                    b.ToTable("ImmobilienOverviews");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImmobilienTypes");
                });

            modelBuilder.Entity("BE.Domain.Entities.Bruttomietrendite", b =>
                {
                    b.HasOne("BE.Domain.Entities.ImmobilienOverview", "ImmobilienOverview")
                        .WithOne("Bruttomietrendite")
                        .HasForeignKey("BE.Domain.Entities.Bruttomietrendite", "ImmobilienOverviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BE.Domain.Entities.QuadratmeterMonatJahr", "Kaltmiete", b1 =>
                        {
                            b1.Property<int>("BruttomietrenditeId")
                                .HasColumnType("int");

                            b1.Property<decimal>("ProJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProQuadratmeter")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("BruttomietrenditeId");

                            b1.ToTable("BruttoMietrenditen");

                            b1.WithOwner()
                                .HasForeignKey("BruttomietrenditeId");
                        });

                    b.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "UmlagefaehigesHausgeld", b1 =>
                        {
                            b1.Property<int>("BruttomietrenditeId")
                                .HasColumnType("int");

                            b1.Property<decimal>("InProzent")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("BruttomietrenditeId");

                            b1.ToTable("BruttoMietrenditen");

                            b1.WithOwner()
                                .HasForeignKey("BruttomietrenditeId");
                        });

                    b.OwnsOne("BE.Domain.Entities.QuadratmeterMonatJahr", "Warmmiete", b1 =>
                        {
                            b1.Property<int>("BruttomietrenditeId")
                                .HasColumnType("int");

                            b1.Property<decimal>("ProJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProQuadratmeter")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("BruttomietrenditeId");

                            b1.ToTable("BruttoMietrenditen");

                            b1.WithOwner()
                                .HasForeignKey("BruttomietrenditeId");
                        });

                    b.Navigation("ImmobilienOverview");

                    b.Navigation("Kaltmiete")
                        .IsRequired();

                    b.Navigation("UmlagefaehigesHausgeld")
                        .IsRequired();

                    b.Navigation("Warmmiete")
                        .IsRequired();
                });

            modelBuilder.Entity("BE.Domain.Entities.Hypothek.ImmobilienHypothek", b =>
                {
                    b.HasOne("BE.Domain.Entities.ImmobilienOverview", "ImmobilienOverview")
                        .WithOne("ImmobilienHypothek")
                        .HasForeignKey("BE.Domain.Entities.Hypothek.ImmobilienHypothek", "ImmobilienOverviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BE.Domain.Entities.ProzentBetrag", "Eigenkapital", b1 =>
                        {
                            b1.Property<int>("ImmobilienHypothekId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Betrag")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("InProzent")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ImmobilienHypothekId");

                            b1.ToTable("ImmobilienHypotheken");

                            b1.WithOwner()
                                .HasForeignKey("ImmobilienHypothekId");
                        });

                    b.OwnsOne("BE.Domain.Entities.Hypothek.Kaufnebenkosten", "Kaufnebenkosten", b1 =>
                        {
                            b1.Property<int>("ImmobilienHypothekId")
                                .HasColumnType("int");

                            b1.HasKey("ImmobilienHypothekId");

                            b1.ToTable("ImmobilienHypotheken");

                            b1.WithOwner()
                                .HasForeignKey("ImmobilienHypothekId");

                            b1.OwnsOne("BE.Domain.Entities.ProzentBetrag", "Gesamtnebenkosten", b2 =>
                                {
                                    b2.Property<int>("KaufnebenkostenImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Betrag")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KaufnebenkostenImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KaufnebenkostenImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentBetrag", "Grundbucheintrag", b2 =>
                                {
                                    b2.Property<int>("KaufnebenkostenImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Betrag")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KaufnebenkostenImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KaufnebenkostenImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentBetrag", "GrunderwerbSteuer", b2 =>
                                {
                                    b2.Property<int>("KaufnebenkostenImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Betrag")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KaufnebenkostenImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KaufnebenkostenImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentBetrag", "Maklerprovision", b2 =>
                                {
                                    b2.Property<int>("KaufnebenkostenImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Betrag")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KaufnebenkostenImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KaufnebenkostenImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentBetrag", "Notarkosten", b2 =>
                                {
                                    b2.Property<int>("KaufnebenkostenImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Betrag")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KaufnebenkostenImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KaufnebenkostenImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentBetrag", "Sicherheitspuffer", b2 =>
                                {
                                    b2.Property<int>("KaufnebenkostenImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Betrag")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KaufnebenkostenImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KaufnebenkostenImmobilienHypothekId");
                                });

                            b1.Navigation("Gesamtnebenkosten")
                                .IsRequired();

                            b1.Navigation("Grundbucheintrag")
                                .IsRequired();

                            b1.Navigation("GrunderwerbSteuer")
                                .IsRequired();

                            b1.Navigation("Maklerprovision")
                                .IsRequired();

                            b1.Navigation("Notarkosten")
                                .IsRequired();

                            b1.Navigation("Sicherheitspuffer")
                                .IsRequired();
                        });

                    b.OwnsOne("BE.Domain.Entities.Hypothek.Kreditbelastung", "Kreditbelastung", b1 =>
                        {
                            b1.Property<int>("ImmobilienHypothekId")
                                .HasColumnType("int");

                            b1.HasKey("ImmobilienHypothekId");

                            b1.ToTable("ImmobilienHypotheken");

                            b1.WithOwner()
                                .HasForeignKey("ImmobilienHypothekId");

                            b1.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "GesamtKreditbelastung", b2 =>
                                {
                                    b2.Property<int>("KreditbelastungImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProJahr")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProMonat")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KreditbelastungImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KreditbelastungImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "Sondertilgung", b2 =>
                                {
                                    b2.Property<int>("KreditbelastungImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProJahr")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProMonat")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KreditbelastungImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KreditbelastungImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "Tilgung", b2 =>
                                {
                                    b2.Property<int>("KreditbelastungImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProJahr")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProMonat")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KreditbelastungImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KreditbelastungImmobilienHypothekId");
                                });

                            b1.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "Zinsen", b2 =>
                                {
                                    b2.Property<int>("KreditbelastungImmobilienHypothekId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("InProzent")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProJahr")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<decimal>("ProMonat")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("KreditbelastungImmobilienHypothekId");

                                    b2.ToTable("ImmobilienHypotheken");

                                    b2.WithOwner()
                                        .HasForeignKey("KreditbelastungImmobilienHypothekId");
                                });

                            b1.Navigation("GesamtKreditbelastung")
                                .IsRequired();

                            b1.Navigation("Sondertilgung")
                                .IsRequired();

                            b1.Navigation("Tilgung")
                                .IsRequired();

                            b1.Navigation("Zinsen")
                                .IsRequired();
                        });

                    b.Navigation("Eigenkapital")
                        .IsRequired();

                    b.Navigation("ImmobilienOverview");

                    b.Navigation("Kaufnebenkosten")
                        .IsRequired();

                    b.Navigation("Kreditbelastung")
                        .IsRequired();
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienHausgeld", b =>
                {
                    b.HasOne("BE.Domain.Entities.ImmobilienOverview", "ImmobilienOverview")
                        .WithOne("ImmobilienHausgeld")
                        .HasForeignKey("BE.Domain.Entities.ImmobilienHausgeld", "ImmobilienOverviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BE.Domain.Entities.QuadratmeterMonatJahr", "Hausgeld", b1 =>
                        {
                            b1.Property<int>("ImmobilienHausgeldId")
                                .HasColumnType("int");

                            b1.Property<decimal>("ProJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProQuadratmeter")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ImmobilienHausgeldId");

                            b1.ToTable("ImmobilienHausgeld");

                            b1.WithOwner()
                                .HasForeignKey("ImmobilienHausgeldId");
                        });

                    b.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "NichtUmlagefaehigesHausgeld", b1 =>
                        {
                            b1.Property<int>("ImmobilienHausgeldId")
                                .HasColumnType("int");

                            b1.Property<decimal>("InProzent")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ImmobilienHausgeldId");

                            b1.ToTable("ImmobilienHausgeld");

                            b1.WithOwner()
                                .HasForeignKey("ImmobilienHausgeldId");
                        });

                    b.OwnsOne("BE.Domain.Entities.ProzentMonatJahr", "UmlagefaehigesHausgeld", b1 =>
                        {
                            b1.Property<int>("ImmobilienHausgeldId")
                                .HasColumnType("int");

                            b1.Property<decimal>("InProzent")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProJahr")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ProMonat")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ImmobilienHausgeldId");

                            b1.ToTable("ImmobilienHausgeld");

                            b1.WithOwner()
                                .HasForeignKey("ImmobilienHausgeldId");
                        });

                    b.Navigation("Hausgeld")
                        .IsRequired();

                    b.Navigation("ImmobilienOverview");

                    b.Navigation("NichtUmlagefaehigesHausgeld")
                        .IsRequired();

                    b.Navigation("UmlagefaehigesHausgeld")
                        .IsRequired();
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienOverview", b =>
                {
                    b.HasOne("BE.Domain.Entities.ImmobilienType", "ImmobilienType")
                        .WithMany()
                        .HasForeignKey("ImmobilienTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImmobilienType");
                });

            modelBuilder.Entity("BE.Domain.Entities.ImmobilienOverview", b =>
                {
                    b.Navigation("Bruttomietrendite")
                        .IsRequired();

                    b.Navigation("ImmobilienHausgeld")
                        .IsRequired();

                    b.Navigation("ImmobilienHypothek")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
